# Generated by Django 4.0.4 on 2022-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('niveau', models.PositiveIntegerField(default=1)),
                ('equipement', models.CharField(max_length=50)),
                ('partie', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
