# Generated by Django 4.0.4 on 2022-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu_role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='nom',
            field=models.CharField(default='oui', max_length=30),
        ),
    ]
