# Generated by Django 4.0.4 on 2022-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu_role', '0002_role_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
